# Server 配置
server:
  port: 9300

# Spring 配置
spring:
  profiles:
    active: dev
  application:
    name: order-service
  main:
    banner-mode: log
  servlet:
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 5MB
  mvc:
    path-match:
      matching-strategy: ANT_PATH_MATCHER